version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8081
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - migrate
    restart: unless-stopped

  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/app
    env_file:
      - .env
    restart: "no"
