# Generated by Django 4.2.23 on 2025-07-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_menuitemanalytics"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitemanalytics",
            options={"ordering": ["-date", "-times_ordered"]},
        ),
        migrations.RenameField(
            model_name="menuitemanalytics",
            old_name="orders",
            new_name="times_ordered",
        ),
        migrations.RenameField(
            model_name="menuitemanalytics",
            old_name="quantity_sold",
            new_name="times_viewed",
        ),
        migrations.RenameField(
            model_name="menuitemanalytics",
            old_name="views",
            new_name="total_quantity",
        ),
        migrations.RenameField(
            model_name="menuitemanalytics",
            old_name="revenue",
            new_name="total_revenue",
        ),
        migrations.AddField(
            model_name="menuitemanalytics",
            name="avg_rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="menuitemanalytics",
            name="conversion_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
