# Generated by Django 4.2.23 on 2025-07-22 08:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_kitchenqueue_ordernote_orderstatushistory_and_more"),
        ("analytics", "0003_alter_menuitemanalytics_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularDishAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_name", models.CharField(max_length=200)),
                ("order_count", models.IntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "popular_dish_analytics",
                "ordering": ["-order_count"],
            },
        ),
        migrations.CreateModel(
            name="CompletedOrderAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("preparation_duration", models.DurationField(blank=True, null=True)),
                ("total_items", models.IntegerField()),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=10)),
                ("customer_satisfaction", models.IntegerField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
            options={
                "db_table": "completed_order_analytics",
                "ordering": ["-completion_time"],
            },
        ),
    ]
