# Generated by Django 4.2.23 on 2025-06-27 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationWaitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_date", models.DateField()),
                ("preferred_time", models.TimeField()),
                ("party_size", models.PositiveIntegerField()),
                (
                    "flexible_date",
                    models.BooleanField(default=False, help_text="Flexible with date"),
                ),
                (
                    "flexible_time",
                    models.BooleanField(default=False, help_text="Flexible with time"),
                ),
                (
                    "max_wait_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Maximum days to wait"
                    ),
                ),
                ("notify_by_email", models.BooleanField(default=True)),
                ("notify_by_sms", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "table_preference",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preferred table (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservations.table",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservationAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                ("max_party_size", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_patterns",
                        to="reservations.table",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("table", "day_of_week", "start_time")},
            },
        ),
    ]
