# Generated by Django 5.2.3 on 2025-06-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busmonitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="current_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="current_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
