# Generated by Django 5.2.3 on 2025-06-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="menuitem",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
