# Generated by Django 4.2.23 on 2025-07-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_reservationwaitlist_reservationavailability"),
        ("orders", "0003_kitchenqueue_ordernote_orderstatushistory_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_custome_c9b64a_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_assigne_6402f1_idx",
        ),
        migrations.AddField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                blank=True,
                help_text="Table assignment for dine-in orders",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="reservations.table",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "created_at"], name="orders_orde_custome_242823_idx"
            ),
        ),
    ]
